name: Manual workflow

on:
  push:

jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Cache Composer dependencies
        id: cache-composer
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          
      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: phpstan, composer:2.5.6

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Check composer version
        run: 'sudo cp foo.conf /etc/apache2/sites-available/foo.conf && sudo service apache2 start && sudo a2ensite foo.conf && sudo systemctl reload apache2 && sudo service apache2 status'

      - name: Check php version
        run: php -v

      - name: Check yarn version
        run: yarn -v

      - name: Check node version
        run: node -v
