name: Manual workflow

on:
  push:

jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install MySQL
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "8.0"
          root-password: 'root'

      - name: Setup PHP with Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: phpstan, composer:2.5.6

      - name: Install Apache
        run: 'sudo bash resources/pipeline/apache-install.sh'

      - name: Cache Composer dependencies
        id: cache-composer
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Create Database
        run: "mysql -uroot -proot -e 'CREATE DATABASE pipeline;'"

      - name: Install Composer dependencies
        run: 'composer install --no-dev'

      - name: Switch ENV to TEST
        run: 'echo "APP_ENV=test" > .env && php bin/console cache:clear'

      - name: Create DB schema from Symfony CLI
        run: 'php bin/console doctrine:schema:update --force'

      - name: Cos
        run: 'curl http://pipeline-local.com/product/1'


