name: Manual workflow

on:
  push:

jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Walsie
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "5.7"

      - name: Walsiedwa
        run: mysql -uroot -e 'SELECT version()'

      # - name: Setup MySQL
      #   uses: shogo82148/actions-setup-mysql@v1
      #   with:
      #     distribution: "mysql"
      #     mysql-version: "5.7"
      #     root-password: 'root'
      #     user: 'developer'
      #     password: 'password'

      # - name: Start MySQL
      #   run: 'sudo service mysql start && sudo service mysql reload && mysql --version'