name: Manual workflow

on:
  push:

jobs:
  # This workflow contains a single job called "greet"
  pipeline:
    # The type of runner that the job will run ons
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install MySQL is skipped, because github action has 8.0 version as default
      - name: Install MySQL
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "8.0"
          root-password: 'root'

      - name: Create Database
        run: "mysql -uroot -proot -e 'CREATE DATABASE pipeline;'"

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      
      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Setup PHP with Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:2.5.6

      - name: Switch ENV to TEST
        run: 'echo "APP_ENV=test" > .env'

      - name: Install Composer dependencies
        run: 'composer install'

      - name: NPM install
        run: 'npm install'

      - name: Check assets
        run: |
              npm run build
              git --no-pager diff --name-only

#              bash resources/pipeline/assets-check.sh

      - name: Install Apache
        run: 'sudo bash resources/pipeline/apache-install.sh'
    
      - name: Create DB schema from Symfony CLI
        run: 'php bin/console doctrine:schema:update --force'

      - name: Run PHP unit tests
        run: 'php bin/phpunit'

      - name: Check PHP stan
        run: 'vendor/bin/phpstan analyse src'

      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: general
          status: SUCCESS
          color: good
      
      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: general
          status: FAILED
          color: danger