name: Manual workflow

on:
  push:

jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
        
      - name: Run composer install
        uses: php-actions/composer@v6
        with:
          dev: no
          php_version: 8.2
          version: 2.5.8
          command: install

      - name: Check PHP Version
        run: php -v

      - name: Check composer version
        run: composer -v
