name: Manual workflow

on:
  push:

jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check composer version
        run: composer -v

      - name: Check php version
        run: php -v

      - name: Check yarn version
        run: yarn -v

      - name: Check node version
        run: node -v
