name: Manual workflow

on:
  push:

jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check PHP Version
        run: php -v
              
      - name: Run composer install
        uses: baschny/php-composer-action@v1
        with:
          composer_version: 2
          command: install
