name: Manual workflow

on:
  push:

jobs:
  # This workflow contains a single job called "greet"
  pipeline:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install MySQL
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "8.0"
          root-password: 'root'

      - name: Create Database
        run: "mysql -uroot -proot -e 'CREATE DATABASE pipeline;'"

      - name: Create cache directories
        run: mkdir /tmp/cache/composer

      - name: Cache Composer dependencies
        id: cache-composer
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-${{ hashFiles('**/composer.lock') }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Setup PHP with Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:2.5.6

      - name: Switch ENV to TEST
        run: 'echo "APP_ENV=test" > .env'

      - name: Install Composer dependencies
        run: 'composer install'

      - name: NPM install
        run: 'npm install'

      - name: Build assets
        run: 'npm run build'

      - name: Install Apache
        run: 'sudo bash resources/pipeline/apache-install.sh'
    
      - name: Create DB schema from Symfony CLI
        run: 'php bin/console doctrine:schema:update --force'

      - name: Run PHP unit tests
        run: 'php bin/phpunit'

      - name: Check PHP stan
        run: 'vendor/bin/phpstan analyse src'

      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: general
          status: SUCCESS
          color: good
      
      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: general
          status: FAILED
          color: danger